name: Store Form Data

on:
  push:
    branches:
      - main

jobs:
  store_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append form data to CSV
        run: |
          echo "Name,Sweetness,Ice,Hot,Size,Quantity,Price" >> URT_order/data.csv
          echo "${{ github.event.head_commit.author.name }}," >> URT_order/data.csv
          echo "${{ github.event.head_commit.author.email }}," >> URT_order/data.csv
          echo "${{ github.event.head_commit.author.date }}," >> URT_order/data.csv
          echo "${{ github.event.head_commit.message }}" >> URT_order/data.csv
