name: Store Form Data

on:
  push:
    branches:
      - main

jobs:
  store_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append form data to CSV
        run: |
          echo "name,sweetness,ice,hot,size,quantity,price" >> data.csv
          echo "${{ github.event.head_commit.author.name }}," >> data.csv
          echo "${{ github.event.head_commit.author.email }}," >> data.csv
          echo "${{ github.event.head_commit.author.date }}," >> data.csv
          echo "${{ github.event.head_commit.message }}" >> data.csv
